spring:
  jpa:
    properties:
      hibernate:
        '[format_sql]': true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8081/oauth/check_token
          client-id: checktoken
          client-secret: check123